### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jbruck** [sindresorhus/SublimeLinter-contrib-alex#2]
I find this error occurs when I enable the Alex linter plugin for markdown files. Running alex from the command line seems to work ok (not extensively tested)

I suspect it is similar to the error mentioned here: [IndexError: list index out of range #227](https://github.com/SublimeLinter/SublimeLinter3/issues/227)

> SublimeLinter: error in SublimeLinter daemon: 
> SublimeLinter: -------------------- 
> SublimeLinter: Traceback (most recent call last):
>   File "/home/jonathan/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
>     item = self.q.get(block=True, timeout=self.MIN_DELAY)
>   File "./python3.3/queue.py", line 175, in get
> queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/jonathan/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
>     self.lint(view_id, timestamp)
>   File "/home/jonathan/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
>     self.callback(view_id, timestamp)
>   File "/home/jonathan/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
>     Linter.lint_view(view, filename, code, hit_time, callback)
>   File "/home/jonathan/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 929, in lint_view
>     linter.lint(hit_time)
>   File "/home/jonathan/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 77, in lint
>     super(NodeLinter, self).lint(hit_time)
>   File "/home/jonathan/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1466, in lint
>     start, end = self.highlight.full_line(line)
>   File "/home/jonathan/.config/sublime-text-3/Packages/SublimeLinter/lint/highlight.py", line 200, in full_line
>     start = self.newlines[line] + char_offset
> IndexError: list index out of range
> 
> SublimeLinter: --------------------

**Comment by sindresorhus** [comment]
Closing as I haven't been able to reproduce it and it's really an issue with SubimeLinter. If you still experience this, open an issue on SublimeLinter.
